# Note: For some countries, while we don't show a fiscal number on the form, we generate
# a fake "placeholder" number and send that, instead. See the PlaceholderFiscalNumber
# staging helper.
AR:
  fiscal_number: true
BR:
  fiscal_number: true
CL:
  fiscal_number: true
CO:
  fiscal_number: true
IN:
  street_address: true
  street_number: optional
  city: true
  fiscal_number: optional
UY:
  fiscal_number: true
ZA:
  address: true
