visa:
    bank_code: VI
    group: cc
    countries:
        AR: true
        BR: true
        #       CL: true  #waiting on AstroPay
        CO: true
        IN: true
        MX: true
        PE: true
        UY: true
        ZA: true
mc:
    bank_code: MC
    group: cc
    countries:
        AR: true
        BR: true
        #       CL: true  #waiting on AstroPay
        CO: true
        IN: true
        MX: true
        PE: true
        UY: true
        ZA: true
#magna:  #waiting on AstroPay
#    bank_code: MG
#    group: cc
#    countries:
#       CL: true
amex:
    bank_code: AE
    group: cc
    countries:
        BR: true
        AR: true
        #       CL: true  #waiting on AstroPay
        CO: true
        PE: true
visa-debit:
    bank_code: VD
    group: cc
    countries:
        MX: true
        PE: true
        ZA: true
    sub_text_key: donate_interface-debit
mc-debit:
    bank_code: MD
    group: cc
    countries:
        MX: true
        ZA: true
    sub_text_key: donate_interface-debit
elo:
    bank_code: EL
    group: cc
    countries:
        BR: true
diners:
    bank_code: DC
    group: cc
    countries:
        BR: true
        #       CL: true  #waiting on AstroPay
        CO: true
        PE: true
        UY: true
hiper:
    bank_code: HI
    group: cc
    countries:
        BR: true
mercadolivre:
    bank_code: ML
    group: cc
    countries:
        BR: true
cabal:
    bank_code: CL
    group: cc
    countries:
        AR: true
naranja:
    bank_code: NJ
    group: cc
    countries:
        AR: true
shopping:
    bank_code: TS
    group: cc
    countries:
        AR: true
nativa:
    bank_code: NT
    group: cc
    countries:
        AR: true
cencosud:
    bank_code: CS
    group: cc
    countries:
        AR: true
argen:
    bank_code: AG
    group: cc
    countries:
        AR: true
#cmr:  #waiting on AstroPay
#    bank_code: CM
#    group: cc
#    countries:
#       CL: true
#presto:  #waiting on AstroPay
#    bank_code: PR
#    group: cc
#    countries:
#       CL: true  #waiting on AstroPay
webpay:
    bank_code: WP
    group: cc
    countries:
        CL: true
lider:
    bank_code: LI
    group: cc
    countries:
        UY: true
oca:
    bank_code: OA
    group: cc
    countries:
        UY: true
rupay:
    bank_code: RU
    group: cc
    countries:
        IN: true
pix:
    bank_code: PQ
    label: PIX
    group: cash
    countries:
        BR: true
cash_boleto:
    bank_code: BL
    label: Boletos
    group: cash
    countries:
        BR: true
cash_oxxo:
    bank_code: OX
    label: OXXO
    group: cash
    countries:
        MX: true
    logo: cash-oxxo.png
cash_santander:
    bank_code: SM
    label: Santander
    group: cash
    countries:
        MX: true
    logo: bank-santander.png
cash_bancomer:
    bank_code: BV
    label: Bancomer
    group: cash
    countries:
        MX: true
    logo: cash-bancomer.png
cash_rapipago:
    bank_code: RP
    label: Rapi Pago
    group: cash
    countries:
        AR: true
    logo: cash-rapipago.png
cash_pago_facil:
    bank_code: PF
    label: Pago Facil
    group: cash
    countries:
        AR: true
    logo: cash-pago-facil.png
cash_efecty:
    bank_code: EY
    label: Efecty
    group: cash
    countries:
        CO: true
    logo: cash-efecty.png
pse:
    bank_code: PC
    label: PSE
    group: bt
    countries:
        CO: true
cash_pago_efectivo:
    bank_code: EF
    label: Pago Efectivo
    group: cash
    countries:
        PE: true
    logo: cash-pago-efectivo.png
cash_abitab:
    bank_code: AI
    label: Abitab
    group: cash
    countries:
        UY: true
    logo: cash-abitab.png
    logo_hd:
        2x: cash-abitab_2x.png
        3x: cash-abitab_3x.png
cash_red_pagos:
    bank_code: RE
    label: Red Pagos
    group: cash
    countries:
        UY: true
    logo: cash-red-pagos.png
ach:
  bank_code: IO
  label: ACH
  group: bt
  countries:
    ZA: true
  logo: bank-ach.png
  logo_hd:
    2x: bank-ach_2x.png
    3x: bank-ach_3x.png
webpay_bt:
  bank_code: WP
  label: Webpay
  group: bt
  countries:
    CL: true
  logo: bank-webpay.png
banco_do_brasil:
  bank_code: BB
  label: Banco do Brasil
  group: bt
  countries:
    BR: true
  logo: bank-banco_do_brasil.png
itau:
  bank_code: I
  label: Itau
  group: bt
  countries:
    BR: true
  logo: bank-itau.png
bradesco:
  bank_code: B
  label: Bradesco
  group: bt
  countries:
    BR: true
  logo: bank-bradesco.png
santander:
  bank_code: SB
  label: Santander
  group: bt
  countries:
    BR: true
  logo: bank-santander.png
santander_rio:
  bank_code: SI
  label: Santander
  group: bt
  countries:
    AR: true
  logo: bank-santander.png
bcp:
  bank_code: BC
  label: BCP
  group: bt
  countries:
    PE: true
  logo: bank-bcp.png
  logo_hd:
    2x: bank-bcp_2x.png
    3x: bank-bcp_3x.png
interbank:
  bank_code: IB
  label: Interbank
  group: bt
  countries:
    PE: true
  logo: bank-interbank.png
  logo_hd:
    2x: bank-interbank_2x.png
    3x: bank-interbank_3x.png
bbva:
  bank_code: BP
  label: BBVA
  group: bt
  countries:
    PE: true
  logo: bank-bbva.png
  logo_hd:
    2x: bank-bbva_2x.png
    3x: bank-bbva_3x.png
#india
netbanking:
  bank_code: NB
  label_key: donate_interface-bank-name-netbanking
  group: bt
  countries:
    IN: true
  logo: bank-netbanking.png
  logo_hd:
    2x: bank-netbanking_2x.png
  sub_text_key: donate_interface-bank-name-netbanking
upi:
  bank_code: UI
  label: UPI
  group: bt
  countries:
    IN: true
  logo: bank-upi.png
  logo_hd:
    2x: bank-upi_2x.png
paytmwallet:
  bank_code: PW
  label: PayTM Wallet
  group: bt
  countries:
    IN: true
  logo: bank-paytm.png
  logo_hd:
    2x: bank-paytm_2x.png
