cc:
    is_default: true
    recurring: false
    validation:
        country: true
        name: true
        email: true
cash:
    recurring: false
    validation:
        country: true
        name: true
        email: true
        payment_submethod: false
bt:
    recurring: true
    validation:
      country: true
      name: true
      email: true
      payment_submethod: true
