cb:
    countries:
        FR: true
    group: cc
    logo: card-cb-lg.png
    # For all the rest, our key matches the brandCode
    brandCode: cartebancaire
visa:
    countries:
        AU: true
        CA: true
        FR: true
        GB: true
        IE: true
        IL: true
        JP: true
        NL: true
        NZ: true
        SE: true
        UA: true
        US: true
    group: cc
    logo: card-visa-lg.png
# FIXME: we don't actually want a separate button for visa-debit
# but we DO need it in this array to avoid an exception on return
# to the ResultSwitcher.
visa-debit:
    countries:
        XX: true
    group: cc
mc:
    countries:
        AU: true
        CA: true
        FR: true
        GB: true
        IE: true
        IL: true
        JP: true
        NL: true
        NZ: true
        SE: true
        UA: true
        US: true
    group: cc
    logo: card-mastercard.png
    logo_hd:
        2x: card-mastercard_2x.png
        3x: card-mastercard_3x.png
amex:
    countries:
        AU: true
        CA: true
        FR: true
        GB: true
        IE: true
        IL: true
        JP: true
        NL: true
        NZ: true
        SE: true
        UA: true
        US: true
    group: cc
    logo: card-amex-lg.png
jcb:
    countries:
        AU: true
        IE: true
        JP: true
        NL: true
    group: cc
    logo: card-jcb-lg.png
discover:
    countries:
        IL: true
        US: true
    group: cc
    logo: card-discover-lg.png
rtbt_ideal:
    label: iDEAL
    group: rtbt
    countries:
        NL: true
    logo: iDEAL-klein.gif
    show_single_logo: true
    brandCode: ideal


