cb:
    countries:
        FR: true
    group: cc
visa:
    countries:
        AU: true
        CA: true
        FR: true
        GB: true
        IE: true
        IL: true
        JP: true
        NL: true
        NZ: true
        SE: true
        UA: true
        US: true
    group: cc
visa-debit:
    group: cc
mc:
    countries:
        AU: true
        CA: true
        FR: true
        GB: true
        IE: true
        IL: true
        JP: true
        NL: true
        NZ: true
        SE: true
        UA: true
        US: true
    group: cc
amex:
    countries:
        AU: true
        CA: true
        FR: true
        GB: true
        IE: true
        IL: true
        JP: true
        NL: true
        NZ: true
        SE: true
        UA: true
        US: true
    group: cc
jcb:
    countries:
        AU: true
        IE: true
        JP: true
        NL: true
    group: cc
discover:
    countries:
        IL: true
        US: true
    group: cc
rtbt_ideal:
    group: rtbt
    countries:
        NL: true
interac:
    group: cc
