cb:
    countries:
        FR: true
    group: cc
    logo: card-cb.png
visa:
    countries:
        FR: true
        IL: true
        JP: true
        UA: true
        US: true
    group: cc
    logo: card-visa.png
jcb:
    countries:
        JP: true
    group: cc
    logo: card-jcb.png
mc:
    countries:
        FR: true
        IL: true
        JP: true
        UA: true
        US: true
    group: cc
    logo: card-mc.png
amex:
    countries:
        US: true
        IL: true
        UA: true
    group: cc
    logo: card-amex.png
discover:
    countries:
        IL: true
        US: true
    group: cc
    logo: card-discover.png


