cb:
  countries:
    - FR
  group: cc
visa:
  countries:
    - AU
    - CA
    - FR
    - GB
    - IE
    - IL
    - JP
    - NL
    - NZ
    - SE
    - UA
    - US
  group: cc
visa-debit:
  group: cc
maestro:
  countries:
    - BE
    - RO
  group: cc
mc:
  countries:
    - AU
    - CA
    - FR
    - GB
    - IE
    - IL
    - JP
    - NL
    - NZ
    - SE
    - UA
    - US
  group: cc
amex:
  countries:
    - AU
    - CA
    - FR
    - GB
    - IE
    - IL
    - JP
    - NL
    - NZ
    - SE
    - UA
    - US
  group: cc
jcb:
  countries:
    - AU
    - IE
    - JP
    - NL
  group: cc
discover:
  countries:
    - IL
    - US
  group: cc
rtbt_ideal:
  group: rtbt
  countries:
    - NL
onlineBanking_CZ:
  group: bt
  countries:
    - CZ
sepadirectdebit:
  group: rtbt
  countries:
    - AT
    - BE
    - BG
    - CY
    - DE
    - EE
    - ES
    - FR
    - GR
    - HR
    - IE
    - IT
    - LT
    - LU
    - LV
    - MT
    - NL
    - PT
    - SI
    - SK

#     Countries Adyen says they don't support
#     https://adyen.com/payment-methods/sepa-direct-debit
#    - CH
#    - CZ
#    - DK
#    - HU
#    - 'NO'
#    - PL
#    - RO
#    - SE
interac:
  group: cc
ach:
  group: dd
  countries:
    - US
