visa:
    bank_code: VI
    label_key: donate_interface-card-name-visa
    group: cc
    countries:
        AR: true
        BR: true
#       CL: true  #waiting on AstroPay
        CO: true
        IN: true
        MX: true
        PE: true
        UY: true
    logo: card-visa-lg.png
mc:
    bank_code: MC
    label_key: donate_interface-card-name-mc
    group: cc
    countries:
        AR: true
        BR: true
#       CL: true  #waiting on AstroPay
        CO: true
        IN: true
        MX: true
        PE: true
        UY: true
    logo: card-mastercard.png
    logo_hd:
        2x: card-mastercard_2x.png
        3x: card-mastercard_3x.png
#magna:  #waiting on AstroPay
#    bank_code: MG
#    label: Magna
#    group: cc
#    countries:
#       CL: true
#    logo: card-magna.png
amex:
    bank_code: AE
    label_key: donate_interface-card-name-amex
    group: cc
    countries:
        BR: true
        AR: true
#       CL: true  #waiting on AstroPay
        CO: true
#       IN: true  Investigating errors: https://phabricator.wikimedia.org/T258509
        PE: true
    logo: card-amex-lg.png
visa-debit:
    bank_code: VD
    label: Visa Debit
    group: cc
    countries:
        MX: true
        PE: true
    logo: card-visa-lg.png
    sub_text_key: donate_interface-debit
mc-debit:
    bank_code: MD
    label: Mastercard Debit
    group: cc
    countries:
        MX: true
    logo: card-mastercard.png
    logo_hd:
        2x: card-mastercard_2x.png
        3x: card-mastercard_3x.png
    sub_text_key: donate_interface-debit
elo:
    bank_code: EL
    label: Elo
    group: cc
    countries:
        BR: true
    logo: card-elo.png
diners:
    bank_code: DC
    label: Diners Club
    group: cc
    countries:
        BR: true
#       CL: true  #waiting on AstroPay
        CO: true
        IN: true
        PE: true
        UY: true
    logo: card-dinersclub-lg.png
hiper:
    bank_code: HI
    label: Hipercard
    group: cc
    countries:
        BR: true
    logo: card-hiper.png
mercadolivre:
    bank_code: ML
    label: MercadoLivre
    group: cc
    countries:
        BR: true
    logo: card-mercadolivre.png
cabal:
    bank_code: CL
    label: Cabal
    group: cc
    countries:
        AR: true
    logo: card-cabal.png
naranja:
    bank_code: NJ
    label: Naranja
    group: cc
    countries:
        AR: true
    logo: card-naranja.png
shopping:
    bank_code: TS
    label: Tarjeta Shopping
    group: cc
    countries:
        AR: true
    logo: card-shopping.png
nativa:
    bank_code: NT
    label: Nativa
    group: cc
    countries:
        AR: true
    logo: card-nativa.png
cencosud:
    bank_code: CS
    label: Cencosud
    group: cc
    countries:
        AR: true
    logo: card-cencosud.png
argen:
    bank_code: AG
    label: Argencard
    group: cc
    countries:
        AR: true
    logo: card-argencard.png
#cmr:  #waiting on AstroPay
#    bank_code: CM
#    label: CMR
#    group: cc
#    countries:
#       CL: true
#    logo: card-cmr.png
#presto:  #waiting on AstroPay
#    bank_code: PR
#    label: Presto
#    group: cc
#    countries:
#       CL: true  #waiting on AstroPay
#    logo: card-presto.png
webpay:
    bank_code: WP
    label: Webpay
    group: cc
    countries:
        CL: true
    logo: bank-webpay.png
webpay_bt:
    bank_code: WP
    label: Webpay
    group: bt
    countries:
        CL: true
    logo: bank-webpay.png
banco_do_brasil:
    bank_code: BB
    label: Banco do Brasil
    group: bt
    countries:
        BR: true
    logo: bank-banco_do_brasil.png
itau:
    bank_code: I
    label: Itau
    group: bt
    countries:
        BR: true
    logo: bank-itau.png
bradesco:
    bank_code: B
    label: Bradesco
    group: bt
    countries:
        BR: true
    logo: bank-bradesco.png
santander:
    bank_code: SB
    label: Santander
    group: bt
    countries:
        BR: true
    logo: bank-santander.png
santander_rio:
    bank_code: SI
    label: Santander
    group: bt
    countries:
        AR: true
    logo: bank-santander.png
cash_boleto:
    bank_code: BL
    label: Boletos
    group: cash
    countries:
        BR: true
cash_oxxo:
    bank_code: OX
    label: OXXO
    group: cash
    countries:
        MX: true
    logo: cash-oxxo.png
cash_santander:
    bank_code: SM
    label: Santander
    group: cash
    countries:
        MX: true
    logo: bank-santander.png
cash_bancomer:
    bank_code: BV
    label: Bancomer
    group: cash
    countries:
        MX: true
    logo: cash-bancomer.png
cash_rapipago:
    bank_code: RP
    label: Rapi Pago
    group: cash
    countries:
        AR: true
    logo: cash-rapipago.png
cash_pago_facil:
    bank_code: PF
    label: Pago Facil
    group: cash
    countries:
        AR: true
    logo: cash-pago-facil.png
cash_efecty:
    bank_code: EY
    label: Efecty
    group: cash
    countries:
        CO: true
    logo: cash-efecty.png
pse:
    bank_code: PC
    label: PSE
    group: bt
    countries:
        CO: true
cash_pago_efectivo:
    bank_code: EF
    label: Pago Efectivo
    group: cash
    countries:
        PE: true
    logo: cash-pago-efectivo.png
cash_red_pagos:
    bank_code: RE
    label: Red Pagos
    group: cash
    countries:
        UY: true
    logo: cash-red-pagos.png
#india
netbanking:
    bank_code: NB
    label_key: donate_interface-bank-name-netbanking
    group: bt
    countries:
        IN: true
    logo: bank-netbanking.png
    logo_hd:
        2x: bank-netbanking_2x.png
    sub_text_key: donate_interface-bank-name-netbanking
upi:
    bank_code: UI
    label: UPI
    group: bt
    countries:
        IN: true
    logo: bank-upi.png
    logo_hd:
        2x: bank-upi_2x.png
paytmwallet:
    bank_code: PW
    label: PayTM Wallet
    group: bt
    countries:
        IN: true
    logo: bank-paytm.png
    logo_hd:
        2x: bank-paytm_2x.png
rupay:
    bank_code: RU
    label: RuPay
    group: cc
    countries:
        IN: true
    logo: card-rupay.png
    logo_hd:
        2x: card-rupay_2x.png
